# Generated by Django 2.0.1 on 2018-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, verbose_name="Nom de l'objet")),
                ('Designation', models.CharField(default='NGC ', max_length=50, verbose_name="Désignation de l'objet")),
                ('Type_objet', models.CharField(choices=[('Galaxie', 'Galaxie'), ('Nébuleuse Diffuse', 'Nébuleuse Diffuse'), ('Nébuleuse Planétaire', 'Nébuleuse Planétaire'), ('Amas Globulaire', 'Amas Globulaire'), ('Amas Ouvert', 'Amas Ouvert')], max_length=50, verbose_name="Type d'objet")),
                ('Instrument', models.CharField(max_length=50, verbose_name='Instrument')),
                ('Imageur', models.CharField(max_length=50, verbose_name='Imageur')),
                ('Monture', models.CharField(max_length=50, verbose_name='Monture')),
                ('Instrument_Guidage', models.CharField(max_length=50, verbose_name='Instrument de Guidage')),
                ('Imageur_Guidage', models.CharField(max_length=50, verbose_name='Imageur de Guidage')),
                ('Reducteur', models.CharField(max_length=50, verbose_name='Reducteur/Correcteur de Focale')),
                ('Logiciels', models.CharField(max_length=60, verbose_name='Logiciels')),
                ('Date', models.DateField()),
                ('Nombre_Pose', models.IntegerField(verbose_name='Nombre de pose total')),
                ('Temps_Pose', models.IntegerField(verbose_name='Temps de pose unitaire')),
                ('Integration', models.FloatField(verbose_name='Temps de pose total')),
                ('Darks', models.IntegerField(verbose_name='Nombre de Darks')),
                ('Flats', models.IntegerField(verbose_name='Nombre de Flats')),
                ('Bias', models.IntegerField(verbose_name='Nombre de Bias')),
                ('Lunaison', models.FloatField(verbose_name='Pourcentage de Lune')),
                ('FWHM', models.FloatField(verbose_name='FWHM moyenne')),
                ('Temperature', models.IntegerField(verbose_name='Température')),
                ('Lieu', models.CharField(max_length=60, verbose_name='Lieu de Photo')),
                ('Image_upload', models.ImageField(upload_to='Media/', verbose_name='Image')),
            ],
        ),
    ]
