# Generated by Django 2.0.1 on 2018-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prenom')),
                ('description', models.CharField(max_length=450, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
