# Generated by Django 2.0.1 on 2018-06-07 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20180605_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 7, 14, 25, 35, 434828, tzinfo=utc)),
        ),
    ]
